# Generated by Django 3.0.4 on 2020-03-09 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
